# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

"""Build a one-scroll HTML contact sheet of the paper figures.

Part of the reproduction *harness* (invoked by ``make figures``); it is not part
of the paper's methods and adds no plotting logic of its own. The figure PNGs are
produced by the submitted experiment scripts under ``figures/``; this script only
lays them out in ``figures/index.html`` with a caption per figure so each can be
eyeballed against the manuscript in one scroll (README "Validation" item 3).

Pure standard library. Run from anywhere; paths resolve relative to the
repository root:

    python figure_index.py

The paper's figure *numbers* are not tracked in this repo, so the captions
describe what each figure plots; match them to the manuscript by content.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent
FIGURES = ROOT / "figures"

# (figure filename, short title, content caption). One entry per PNG the
# experiment scripts write into figures/.
FIGURES_SPEC = [
    (
        "exp1_monte_carlo.png",
        "Exp 1 - Monte-Carlo risk law",
        "MSE vs noise level sigma, one panel per smoothness order p.",
    ),
    (
        "exp2_kp_scaling.png",
        "Exp 2 - constants vs order",
        "Sharp minimax shape-quality constant vs smoothness order p.",
    ),
    (
        "exp3_filter_comparison.png",
        "Exp 3 - BB-family vs Savitzky-Golay",
        "Shape-quality K on a common scale, the sub-optimality gap "
        "(% above optimal), and causal SG -> continuous limit.",
    ),
    (
        "exp4_tracking.png",
        "Exp 4 - tracking",
        "Continuous-time benchmark over X_3(D) (g* optimal) and per-trajectory "
        "MSE relative to g* (oracle-tuned per trajectory).",
    ),
    (
        "exp5_delta_sweep.png",
        "Exp 5 - sampled-filter convergence",
        "Relative constant error |K(N) - K_p*| / K_p* vs tap count "
        "N = rho/Delta (effective memory in samples).",
    ),
    (
        "fig_impulse_responses.png",
        "Optimal filter shapes",
        "Filter value vs normalized time (corrected infinite-cascade).",
    ),
    (
        "fig_kernel_sign_changes.png",
        "Peano kernel / knot accumulation",
        "Kernel Phi visible lobes, and distance-to-endpoint vs knot index.",
    ),
]


def build_html() -> tuple[Path, list[str]]:
    """Write figures/index.html; return (path, list of missing PNG names)."""
    cards = []
    missing: list[str] = []
    for fname, title, caption in FIGURES_SPEC:
        if (FIGURES / fname).exists():
            body = f'<img src="{fname}" alt="{fname}">'
        else:
            missing.append(fname)
            body = (
                '<p class="missing">figure not found -- run '
                "<code>make figures</code> to regenerate</p>"
            )
        cards.append(
            "<section>\n"
            f"  <h2>{title}</h2>\n"
            f'  <p class="cap">{caption}</p>\n'
            f'  <p class="file">{fname}</p>\n'
            f"  {body}\n"
            "</section>"
        )
    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Paper figures - reproduction</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 1000px; margin: 2rem auto;
         padding: 0 1rem; color: #1a1a1a; }}
  h1 {{ font-size: 1.4rem; }}
  section {{ margin: 2.5rem 0; border-top: 1px solid #ddd; padding-top: 1rem; }}
  h2 {{ font-size: 1.1rem; margin: 0 0 .25rem; }}
  .cap {{ margin: .25rem 0; color: #333; }}
  .file {{ margin: .1rem 0 .75rem; color: #888; font-family: monospace;
           font-size: .85rem; }}
  img {{ width: 100%; height: auto; border: 1px solid #eee; }}
  .missing {{ color: #b00; font-style: italic; }}
</style>
</head>
<body>
<h1>Reproduction figures &mdash; compare against the manuscript</h1>
<p>Regenerated by <code>make figures</code> from the submitted experiment
scripts. The figures/ directory (including this page) is not tracked.</p>
{chr(10).join(cards)}
</body>
</html>
"""
    FIGURES.mkdir(exist_ok=True)
    index = FIGURES / "index.html"
    index.write_text(html)
    return index, missing


def main() -> int:
    index, missing = build_html()
    print("== figures ==")
    for fname, title, _ in FIGURES_SPEC:
        mark = "MISS" if fname in missing else "ok  "
        print(f"  [{mark}] {fname:32s} {title}")
    print(f"\nopen {index}")
    if missing:
        print(f"\nWARNING: {len(missing)} figure(s) missing: {', '.join(missing)}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
